version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jewelry-shop-backend
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/jewelry-shop
      - PORT=8000
    depends_on:
      - mongodb
    networks:
      - jewelry-shop-network

  mongodb:
    image: mongo:latest
    container_name: jewelry-shop-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - jewelry-shop-network

networks:
  jewelry-shop-network:
    driver: bridge

volumes:
  mongodb-data:
